### PR TITLE
Fit Python 3 API compatibility writing bytes

### PR DESCRIPTION
**Pull request by ammirate**

### CODE REVIEW

**Comment by michamos** [comment]
I don't think that's right: if opened in binary mode, you should write bytes. If opened in text mode, you should write strings. I chose the first option in my PR. Are you sure it's wrong?

**Comment by ammirate** [comment]
This is related to this error: ```TypeError: write() argument must be str, not bytes```, which makes the build still failing. Do you think this is not the right thing?

**Comment by michamos** [comment]
the build of inspirehep/inspire-schemas#149 is failing because the bugfix has not been released on PyPI, so it is still using the old buggy version.

**Comment by ammirate** [comment]
Actually, I have uploaded a new version this morning after merging your PR.

**Comment by michamos** [comment]
Are you sure you uploaded the right version? looking at the tarball there, it doesn't contain the fix.

**Comment by michamos** [comment]
Indeed, this was not needed, now it fails for a different reason (fixed by #5 )

**Pull request closed without merging**
